# Generated by Django 2.2.2 on 2023-10-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='middlename',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='nic',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
