# Generated by Django 2.2.2 on 2023-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20231023_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='mobileno1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mobileno2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
