# Generated by Django 2.2.2 on 2023-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20231023_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_img',
            field=models.ImageField(blank=True, default='photos/1.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
